# swagger.yml

openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about players and notes"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Player:
      type: "object"
      required:
        - lname
      properties:
        fname:
          type: "string"
        lname:
          type: "string"

paths:
  /players:
    get:
      operationId: "players.read_all"
      tags:
        - "Players"
      summary: "Read the list of players"
      responses:
        "200":
          description: "Successfully read players list"
    post:
      operationId: "players.create"
      tags:
      - Players
      summary: "Create a person"
      requestBody:
        description: "Person to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "person"
              $ref: "#/components/schemas/Player"
      responses:
        "201":
          description: "Successfully created person"